name: 'Build'

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BUILD_TOKEN }}
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: echo 'Generated shared code' > README.md
      - uses: actions-x/commit@v2.9
        with:
          files: dist src README.md
          force: true
          branch: deployment
          message: 'Automatically build common (GitHub Actions)'
          token: ${{ secrets.BUILD_TOKEN }}
