name: 'Build'

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: echo ${{ secrets.BUILD_TOKEN }}
      - uses: github-actions-x/commit@v2.9
        with:
          push-branch: deployment
          commit-message: 'Build common'
          github-token: ${{ secrets.BUILD_TOKEN }}
          
